title: DevFest Perros-Guirec
description: >- # this means to ignore newlines until "baseurl:"
  DevFestNoz rassemble les développeu.se.r.s en soirée pour apprendre et partager ensemble lors de conférences et ateliers organisés par l'association Code d'Armor à Lannion et Perros-Guirec.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com



# Build settings
plugins:
  - jekyll_asset_pipeline

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .sass-cache/
   - Gemfile
   - .github/
   - README.md

sass:
  style: compressed # or expanded, depending on your preference

asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  display_path: nil
  gzip: false