baseurl: "https://devfest.codedarmor.fr/"
title: "DevFest Perros"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "DevFest Perros-Guirec"
  Description: "sur de la côte de granit rose"
  Date: "7 octobre"
  Price: "30€"
  Venue: "Palais des Congrès"
  Address: "1 Rue du Maréchal Foch"
  City:  "Perros-Guirec"
  State: "France"
  Images: ["/img/cover.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    #- location
    #- speakers
    #- schedule
    #- sponsors
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "A propos"
    location: "Location"
    speakers: "Speakers"
    schedule: "Programme"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: " Billetterie "
    link: "https://www.billetweb.fr/devfest-perros-guirec"

  # List of Sponsors
  Sponsors:
    - name: "Sponsor1"
      logo: "/img/sponsor1.png"
      url: "http://www.codedarmor.fr"

  # List of Partners
  Partners:
    #- name: "Anticipa"
    #  logo: "/img/partners/anticipa.png"
    #  url: "https://www.technopole-anticipa.com/french-tech-lannion/"

  Speakers:
#    - name: "Philippe Ensarguet"
#      ref: "philippe"
#      photo: "/img/speakers/philippe.jpg"
#      bio: "As Chief Technology Officer, Philippe is leading the network-native to digital technology strategy, orientations and tech cultural transformation for Orange Business Services. With 25+ years of experience, he has a privileged viewpoint on tech stacks and platforms, build to ops practices and tools, as well as on the cultural transformations undertaken by customers, partners and teams. Philippe frequently shares his observations and trends via keynotes, sessions or conferences. Pro-software cultured, cloud minded and digital addicted, he brings expertise, analysis and leadership to executives and companies in their global tech innovations and transformations. With a deep understanding of partners and Open Source ecosystems, he is actively scouting to identify the most strategic and disruptive partners. Advisor for 2 startups in tech, Weaveworks and Cycloid. MTB and Gravel addicted on his spare time."
#      company: "AWS"

  # The entire schedule
  Schedule:
#    - name: "Ouverture des portes"
#      time: "8h45"
#    - name: "Intro"
#      time: "9h20"
#    - name: "Philippe Ensarguet"
#      company: "CTO OBS"
#      speakers:
#        - name: "Philippe Ensarguet"
#          ref: "philippe"
#          photo: "/img/speakers/philippe.jpg"
#      presentation:
#        title: "Keynote"
#        description: "Surprise !"
#        time: "9h30"

