baseurl: "https://devfest.codedarmor.fr/"
title: "DevFest Perros"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "DevFest Perros-Guirec"
  Description: "sur de la côte de granit rose"
  Date: "7 octobre"
  Price: "30€"
  Venue: "Palais des Congrès"
  Address: "1 Rue du Maréchal Foch"
  City:  "Perros-Guirec"
  State: "France"
  Images: ["/img/cover.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    #- location
    - speakers
    #- schedule
    #- sponsors
    - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "A propos"
    location: "Location"
    speakers: "Speakers"
    schedule: "Programme"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: " Billetterie "
    link: "https://www.billetweb.fr/devfest-perros-guirec"

  # List of Sponsors
  Sponsors:
    - name: "Sponsor1"
      logo: "/img/sponsor1.png"
      url: "http://www.codedarmor.fr"

  # List of Partners
  Partners:
    - name: "DCbrain"
      logo: "/img/partners/dcbrain.png"
      url: "https://dcbrain.com/"

  Speakers:
    - name: "Héloïse Dano"
      ref: "heloise"
      photo: "/img/speakers/heloise.jpg"
      bio: "Avec sa société ecologeek, Héloïse tente d'initier le plus de personnes possible aux pratiques du Numérique Responsable. Fervente partisane de l'utilisation de l'intelligence collective elle utilise au maximum des méthodes participatives et collaborative pour faire comprendre les messages clés tout en passant un bon moment. Elle est également membre du CA de l'association de la Fresque Du Numérique et participe activement à de nombreux collectifs et groupes de travail autour de ce sujet. Bretonne depuis toujours elle a à coeur de développer un réseau local pour parler du Numérique Responsable jusqu'au fin fond du Finistère ;)"
      company: "Ecologeek"
    - name: "Olivier Le Goaër"
      ref: "olivier"
      photo: "/img/speakers/olivier.png"
      bio: "Titulaire d'un Doctorat en Informatique de l'Université de Nantes, Olivier Le Goaër est actuellement enseignant-chercheur à l'Université de Pau et des Pays de l'Adour. Son thème de recherche est le Génie Logiciel (Vert). Il est responsable scientifique de la branche Mobile (Android et bientôt iOS) du projet Open Source ecoCode, basé sur SonarQube. Il milite pour l'introduction du Numérique Responsable dans les formations universitaires et d'ingénieurs en Informatique."
      company: "Université de Pau et des Pays de l'Adour"
    - name: "Tristan Nitot"
      ref: "tristan"
      photo: "/img/speakers/tristan.png"
      bio: "Tristan Nitot, entrepreneur du numérique, fondateur et ex-président de Mozilla Europe (Firefox), co-fondateur d’Unsearch et animateur du podcast l’Octet Vert."
      company: ""
    - name: "Romuald Priol"
      ref: "romuald"
      photo: "/img/speakers/romuald.jpg"
      bio: "Passionné d’écologie, de good-tech, d’éthique et de performance informatique, je suis développeur expert en web-performance au quotidien, représentant du collectif numérique responsable de GreenIt.fr et ambassadeur formation chez thegreencompagnon. J’essaye de promouvoir l’évolution du numérique en le rendant responsable : pour un numérique plus « green », plus « performant », plus « éthique » et plus « accessible »."
      company: ""
    - name: "Sylvain Revereault"
      ref: "sylvain"
      photo: "/img/speakers/sylvain.jpg"
      bio: "Travaillant depuis une vingtaine d’années dans l’informatique, je me suis progressivement spécialisé dans les technologies systèmes et réseaux, en particulier autour des systèmes GNU/Linux, avant de m’orienter vers les thématiques DevOps et de l'agilité dans le monde “Ops”. En complément des facettes techniques, j'explore les aspects collaboratifs et les approches innovantes de management, et j'ai consacré ces deux dernières années à monter en compétences sur les liens de nos métiers avec l'écologie. Je suis actuellement consultant autour des thématiques DevOps, Management 3.0 et Green IT chez Zenika, tout en portant la casquette de CTO de l’agence de Rennes." 
      company: "Zenika"
    - name: "Pierre Rust"
      ref: "pierre"
      photo: "img/speakers/pierre.jpg"
      bio: "Développeur et chercheur chez Orange, je travaille sur l'empreinte environnementale du numérique et sur sa réduction."
      company: "Orange"


  # The entire schedule
  Schedule:
#    - name: "Ouverture des portes"
#      time: "8h45"
#    - name: "Intro"
#      time: "9h20"
#    - name: "Philippe Ensarguet"
#      company: "CTO OBS"
#      speakers:
#        - name: "Philippe Ensarguet"
#          ref: "philippe"
#          photo: "/img/speakers/philippe.jpg"
#      presentation:
#        title: "Keynote"
#        description: "Surprise !"
#        time: "9h30"

