baseurl: "https://devfest.codedarmor.fr/"
title: "DevFest Perros"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "DevFest Perros-Guirec"
  Description: "sur de la côte de granit rose"
  Date: "6 octobre 2023"
  Price: "30€"
  Venue: "Palais des Congrès"
  Address: "1 Rue du Maréchal Foch"
  City:  "Perros-Guirec"
  State: "France"
  Images: ["/img/cover.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    #- location
    - speakers
    #- schedule
    #- sponsors
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "A propos"
    location: "Location"
    speakers: "Speakers"
    schedule: "Programme"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: " Billetterie "
  #  link: "https://www.billetweb.fr/devfest-perros-guirec"

  # The Press Link in the menu
  # If you don't want this, just comment the press property.
  #Press:
  #  text: "Dossier de Presse"
  #  link: "./doc/DevFest-Perros-Guirec.pdf"

  # List of Sponsors
  Sponsors:
    - name: "DCbrain"
      logo: "/img/partners/dcbrain.png"
      url: "https://dcbrain.com/"
    
    - name: "Eco-Compteur"
      logo: "/img/partners/ecocompteur.png"
      url: "https://www.eco-compteur.com/"

  # List of Partners
  Partners:
    - name: "Anticipa"
      logo: "/img/partners/anticipa.png"
      url: "https://www.technopole-anticipa.com/french-tech-lannion/"

  Speakers:
    - name: "Tugdual Grall"
      ref: "tugdual"
      photo: "/img/speakers/tugdual.jpg"
      bio: "Tugdual Grall, est Solutions Engineer chez GitHub, où il accompagne les développeurs dans leur utilisation de GitHub et des pratiques DevOps/DevSecOps.
      Avant de travailler chez GitHub, 'Tug', était, DevRel chez Redis, Directeur du Product Management chez Red Hat, Technical Evangelist chez MapR, MongoDB et Couchbase. Tug a également travaillé comme CTO chez eXo Platform, et comme Product Manager et Développeur sur la platform JavaEE d'Oracle.
      Tugdual est également co-fondateur du Nantes JUG (Java Users Group) qui réunit tous les mois depuis 2008 les développeurs et architectes de la région nantaise."
      company: "GitHub"
    - name: "Julien Salvi"
      ref: "julien"
      photo: "/img/speakers/julien.png"
      bio: "Into the Android world for 10 years, I experienced California the startup way of life before coming back to France. I am currently a Lead Android Engineer at Aircall where we are building the best phone system for modern businesses. Alongside Android, I have a great interest in backend development with Kotlin and AR/VR technology. In 2021, I became an Android GDE to continue my journey to always share and learn with the Android community. On my spare time, I am a world traveler and a beer lover always looking for the best IPAs!"
      company: "Aircall"
    - name: "Eléa Petton"
      ref: "elea"
      photo: "/img/speakers/elea.jpg"
      bio: "Etudiante pendant cinq ans à l'école d'ingénieurs ISEN Brest, je suis diplômée en octobre 2022 en tant qu'ingénieur généraliste avec une coloration Intelligence Artificielle (IA).
      L'IA est un domaine qui me passionne et dans lequel je me spécialise en intégrant la TEAM AI Solutions d'OVHcloud en tant que Machine Learning Engineer.
      Je travaille sur trois produits d'OVHcloud dédiés à l'entraînement et au déploiement de modèles d'IA : AI Training, AI Notebooks et AI Deploy. Mon rôle est de créer des verticaux sur ces produits sous différents formats pour les utilisateurs de la plateforme."
      company: "OVHcloud"
    - name: "Stephane Cauchy"
      ref: "stephane"
      photo: "/img/speakers/stephane.jpg"
      bio: 'Host leader du Laboratoire d’expérimentation digitale (LED) de BPCE-SI, incubateur sur les nouveaux usages, pratiques et outils au service d’une édition logicielle toujours plus performante. Auteur du livre 'Etre agile par nature' qui retrace les débuts de la transformation agile chez BPCE. Près de 40 ans d'expérience, spécialiste de l'agilité d'entreprise et coach d'organisation."
      company: "BPCE-SI"
    - name: "LIU Yung"
      ref: "liu"
      photo: "/img/speakers/liu.jpg"
      bio: "Directeur délégué - Responsable de domaine STS (SOLUTIONS TECHNOLOGIQUES DU SI )"
      company: "BPCE-SI"
    - name: "Thomas Fournaise"
      ref: "thomas"
      photo: "/img/speakers/thomas.jpg"
      bio: "Directeur délégué - Responsable de domaine STS (SOLUTIONS TECHNOLOGIQUES DU SI )"
      company: "Nickel"
    - name: "Julie Rabette"
      ref: "julie"
      photo: "/img/speakers/julie.jpg"
      bio: "Apres plus de 10 ans a alterner les missions de dev Java et de test, j'ai eu la chance de faire partie des premieres personnes a Nokia Lannion
      a travailler sur le remplacement d'algo 'classique' de la couche L1 de la 5G par du deepLearning en vue de l'integration sur accelerateur HW ML specific
      depuis novembre nous avons pour objectif d'ameliorer les performances et nous travaillons sur la mise en place de la QAT sur le model."
      company: "Nokia"
    - name: "Alexandre Lou"
      ref: "alexandre"
      photo: "/img/speakers/alexandre.jpg"
      bio: "Aujourd'hui ingénieur MLOps chez Nokia, j'ai commencé en tant que stagiaire sur des problématiques Machine learning. Dans la continuité de ces travaux, je contribue à la création d'environnements dédiés aux projets"
      company: "Nokia"


  # The entire schedule
  Schedule:
    - name: "Ouverture des portes"
      time: "8h45"
    - name: "Intro"
      time: "9h15"
    - name: "Héloïse Dano"
      company: "Héloïse Dano (Ecologeek)"
      speakers:
        - name: "Héloïse Dano"
          ref: "heloise"
          photo: "/img/speakers/heloise.jpg"
      presentation:
        title: "Numérique responsable"
        description: "Quels sont les impacts environnementaux, sociaux et sociétaux du numérique.? Le Numérique Responsable c’est quoi ? Comment il répond à ces problématiques ? Quelles sont les grandes pistes d'actions à notre échelle de dev ? On tentera de répondre ensemble à ces questions lors de cette conférence interactive. (Re)voir les bases pour aller dans la bonne direction ça fait pas de mal ;)"
        time: "9h30"
    - name: "Tristan Nitot"
      company: "Tristan Nitot (Scaleway)"
      speakers:
        - name: "Tristan Nitot"
          ref: "tristan"
          photo: "/img/speakers/tristan.png"
      presentation:
        title: ""
        description: "L'été 2022, avec sa sécheresse et ses multiples canicules en Europe, ses inondations au Pakistan nous permet de vivre le dérèglement climatique de près. Mais quels sont les rapports entre 
        le changement climatique et le numérique ? Ce dernier fait-il partie de la solution ou du problème ? Que peut-on faire personnellement et professionnellement à notre niveau ? Ce sont ces sujets qui seront 
        abordés successivement dans cete intervention."
        time: "10h30"
    - name: "Café"
      time: "11h15"
    - name: "Sylvain Revereault"
      company: "Sylvain Revereault (Zenika)"
      speakers:
        - name: "Sylvain Revereault"
          ref: "sylvain"
          photo: "/img/speakers/sylvain.jpg"
      presentation:
        title: "Impacts environnementaux du Cloud : the good, the bad, the ugly"
        description: "Le Cloud est un outil formidable qui facilite notre quotidien, nous permet de travailler plus vite, de mettre en place des architectures dont nous n'osions pas rêver il y a encore quelques années.

Parmi les promesses du Cloud, il y a celle du Green IT : en utilisant le Cloud, nous pourrions réduire l'empreinte environnementale de nos activités. Mais qu'en est-il réellement de cette promesse ?

C'est ce que nous explorerons lors de cette présentation, en nous penchant tout d'abord sur les impacts environnementaux de l'informatique au sens large, puis en nous focalisant sur les aspects hébergements, et enfin en regardant ce que les grands acteurs du Cloud mettent en place pour réduire leurs impacts."
        time: "11h30"
    - name: "Déjeuner"
      time: "12h15"
    - name: "Romuald Priol"
      company: "Romuald Priol (Association Green IT)"
      speakers:
        - name: "Romuald Priol"
          ref: "romuald"
          photo: "/img/speakers/romuald.jpg"
      presentation:
        title: "Numérique responsable : Comment lier performance et écologie ?"
        description: "Contrairement à ce que l'on pourrait croire, la performance n'est pas forcément \"green\", et ça n'est pas parce que vous avez de très bons scores sur les outils d'analyse de performance que votre application est écoconçue ! Nous allons voir comment développer une application de la façon \"responsable\" en comprenant les différents problèmes écologiques du numérique tout en passant en revue les bonnes (ou mauvaises) pratiques de web-performance et les outils pouvant améliorer votre code."
        time: "14h00"
    - name: "Pierre Rust"
      company: "Pierre Rust (Orange)"
      speakers:
        - name: "Pierre Rust"
          ref: "pierre"
          photo: "/img/speakers/pierre.jpg"
      presentation:
        title: "Outils d\'empreinte carbone des cloud public : comparer des pommes et des oranges"
        description: "L\'hébergement, et en particulier les data-centers, a un impact environnemental, mais on ne sait généralement pas estimer combien il représente sur nos projets. Depuis quelques mois, tous les grands fournisseurs de cloud public vous proposent des outils pour estimer le CO2 émis par les ressources cloud que vous utilisez. Malheureusement, il n\'existe pas de méthodologie commune pour ces estimations et chaque acteur compte un peu ce qu\'il veut ! Venez voir ce qui se cache derrières les \"calculettes carbones\" de GCP, Azure et AWS, ce qu'ils prennent en compte et ce qu'ils négligent."
        time: "14h45"
    - name: "break"
      time: "15h30"
    - name: "Olivier Le Goaër"
      company: "Olivier Le Goaër (Université de Pau)"
      speakers:
        - name: "Olivier Le Goaër"
          ref: "olivier"
          photo: "/img/speakers/olivier.png"
      presentation:
        title: "ecoCode mobile: how green is your app?"
        description: "Tandis que de plus en plus d’acteurs s’intéressent à l’éco-conception des sites Web, peu de travaux se sont intéressés aux apps mobile alors que ces dernières représentent un défi environnemental encore plus gigantesque.

Mais comment former la future génération de développeurs mobile à l’écriture d’un code plus écologique ?

Pour tenter de répondre à cette question, cette présentation introduit un catalogue spécifique de code smells pour Android ainsi qu’un plugin SonarQube pour les faire respecter."
        time: "15h45"
    - name: "Olivier Ridoux"
      company: "Olivier Ridoux (IRISA)"
      speakers:
        - name: "Olivier Ridoux"
          ref: "olivier_ridoux"
          photo: "/img/speakers/olivier_ridoux.png"
      presentation:
        title: "Moins vite, moins haut, moins fort : une devise pour le Green IT"
        description: "Le Green IT est souvent abordé comme faire autant voire plus avec moins, c’est-à-dire éliminer les impacts qui ne seraient pas essentiels à la réalisation d’une fonctionnalité désirée.
Nous allons proposer de l’aborder comme faire délibérément moins, avec encore moins, c’est-à-dire éliminer les exigences, et donc les fonctionnalités, qui seraient les plus impactantes.
Nous présenterons des exemples concrets et d’autres encore imaginaires, mais pas improbables, à l’appui de la devise « Moins vite, moins haut, moins fort »"
        time: "16h30"
    - name: "Fin"
      time: "17h30"

