baseurl: "https://devfest.codedarmor.fr/"
title: "DevFest Perros"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "DevFest Perros-Guirec"
  Description: "sur de la côte de granit rose"
  Date: "6 octobre 2023"
  Price: "30€"
  Venue: "Palais des Congrès"
  Address: "1 Rue du Maréchal Foch"
  City:  "Perros-Guirec"
  State: "France"
  Images: ["/img/cover.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    #- location
    - speakers
    - schedule
    #- sponsors
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "A propos"
    location: "Location"
    speakers: "Speakers"
    schedule: "Programme"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: " Billetterie "
  #  link: "https://www.billetweb.fr/devfest-perros-guirec"

  # The Press Link in the menu
  # If you don't want this, just comment the press property.
  #Press:
  #  text: "Dossier de Presse"
  #  link: "./doc/DevFest-Perros-Guirec.pdf"

  # List of Sponsors
  Sponsors:
    - name: "DCbrain"
      logo: "/img/partners/dcbrain.png"
      url: "https://dcbrain.com/"
    
    - name: "Eco-Compteur"
      logo: "/img/partners/ecocompteur.png"
      url: "https://www.eco-compteur.com/"

  # List of Partners
  Partners:
    - name: "Anticipa"
      logo: "/img/partners/anticipa.png"
      url: "https://www.technopole-anticipa.com/french-tech-lannion/"

  Speakers:
    - name: "Tugdual Grall"
      ref: "tugdual"
      photo: "/img/speakers/tugdual.jpg"
      bio: "Tugdual Grall, est Solutions Engineer chez GitHub, où il accompagne les développeurs dans leur utilisation de GitHub et des pratiques DevOps/DevSecOps.
      Avant de travailler chez GitHub, 'Tug', était, DevRel chez Redis, Directeur du Product Management chez Red Hat, Technical Evangelist chez MapR, MongoDB et Couchbase. Tug a également travaillé comme CTO chez eXo Platform, et comme Product Manager et Développeur sur la platform JavaEE d'Oracle.
      Tugdual est également co-fondateur du Nantes JUG (Java Users Group) qui réunit tous les mois depuis 2008 les développeurs et architectes de la région nantaise."
      company: "GitHub"
    - name: "Julien Salvi"
      ref: "julien"
      photo: "/img/speakers/julien.png"
      bio: "Into the Android world for 10 years, I experienced California the startup way of life before coming back to France. I am currently a Lead Android Engineer at Aircall where we are building the best phone system for modern businesses. Alongside Android, I have a great interest in backend development with Kotlin and AR/VR technology. In 2021, I became an Android GDE to continue my journey to always share and learn with the Android community. On my spare time, I am a world traveler and a beer lover always looking for the best IPAs!"
      company: "Aircall"
    - name: "Eléa Petton"
      ref: "elea"
      photo: "/img/speakers/elea.jpg"
      bio: "Etudiante pendant cinq ans à l'école d'ingénieurs ISEN Brest, je suis diplômée en octobre 2022 en tant qu'ingénieur généraliste avec une coloration Intelligence Artificielle (IA).
      L'IA est un domaine qui me passionne et dans lequel je me spécialise en intégrant la TEAM AI Solutions d'OVHcloud en tant que Machine Learning Engineer.
      Je travaille sur trois produits d'OVHcloud dédiés à l'entraînement et au déploiement de modèles d'IA : AI Training, AI Notebooks et AI Deploy. Mon rôle est de créer des verticaux sur ces produits sous différents formats pour les utilisateurs de la plateforme."
      company: "OVHcloud"
    - name: "Stephane Cauchy"
      ref: "stephane"
      photo: "/img/speakers/stephane.jpg"
      bio: "Host leader du Laboratoire d’expérimentation digitale (LED) de BPCE-SI, incubateur sur les nouveaux usages, pratiques et outils au service d’une édition logicielle toujours plus performante. Auteur du livre 'Etre agile par nature' qui retrace les débuts de la transformation agile chez BPCE. Près de 40 ans d'expérience, spécialiste de l'agilité d'entreprise et coach d'organisation."
      company: "BPCE-SI"
    - name: "LIU Yung"
      ref: "liu"
      photo: "/img/speakers/liu.jpg"
      bio: "Directeur délégué - Responsable de domaine STS (SOLUTIONS TECHNOLOGIQUES DU SI )"
      company: "BPCE-SI"
    - name: "Thomas Fournaise"
      ref: "thomas"
      photo: "/img/speakers/thomas.jpg"
      bio: "Passionné d'informatique et de développement depuis longtemps, je suis passé par les équipes projets, l'architecture et l'urbanisme d'entreprise avant de bifurquer vers l'IA et la Data. Je me passionne pour tous les sujets liés aux données, aux biais, à l'IA et à l'éthique. Depuis 2016, j'organise le Salon de la Data à Nantes."
      company: "Nickel"
    - name: "Julie Rabette"
      ref: "julie"
      photo: "/img/speakers/julie.jpg"
      bio: "Apres plus de 10 ans a alterner les missions de dev Java et de test, j'ai eu la chance de faire partie des premieres personnes a Nokia Lannion
      a travailler sur le remplacement d'algo 'classique' de la couche L1 de la 5G par du deepLearning en vue de l'integration sur accelerateur HW ML specific
      depuis novembre nous avons pour objectif d'ameliorer les performances et nous travaillons sur la mise en place de la QAT sur le model."
      company: "Nokia"
    - name: "Alexandre Lou"
      ref: "alexandre"
      photo: "/img/speakers/alexandre.jpg"
      bio: "Aujourd'hui ingénieur MLOps chez Nokia, j'ai commencé en tant que stagiaire sur des problématiques Machine learning. Dans la continuité de ces travaux, je contribue à la création d'environnements dédiés aux projets"
      company: "Nokia"


  # The entire schedule
  Schedule:
    - name: "Tugdual Grall"
      company: "Github"
      speakers:
        - name: "Tugdual Grall"
          ref: "tugdual"
          photo: "/img/speakers/tugdual.jpg"
      presentation:
        title: "Copilot : L’intelligence artificielle au service des développeurs"
        description: "Amis développeurs, vous avez besoin:{{< line_break >}}
        * d’écrire des tests pour vos applications Web/JavaScript ?{{< line_break >}}
        * de compléter une classe Java d’accès aux données ?{{< line_break >}}
        * corriger des bugs dans votre code ?{{< line_break >}}
        * d’ajouter des nouveaux services à votre déploiement Kubernetes, Terraform ?{{< line_break >}}
        * de comprendre du code que vous découvrez en arrivant sur un nouveau projet ?{{< line_break >}}
        Venez découvrir comment GitHub Copilot va vous aider sur ses taches et bien d'autres, et ce directement dans votre IDE favori, et quelque soit votre language de predilection! GitHub Copilot est un outil basé sur le maintenant très connu modèle OpenAI GPT.
        Cette présentation s'appuie principalement sur des démonstrations durant lesquelles Tug montre comment il utilise GitHub Copilot pour développer le site https://windr.org . Venez également avec vos questions & retour d'experience si vous utilisez aujourd'hui Copilot: cette session sera interactive!
        Tug couvrira également GitHub Copilot X, la vision de GitHub de l'IA et le travaille du développeur."
    - name: "Julien Salvi"
      company: "Aircall"
      speakers:
        - name: "Julien Salvi"
          ref: "julien"
          photo: "/img/speakers/julien.png"
      presentation:
        title: "Machine Learning sur Android avec ML Kit (sans être expert en IA)"
        description: "Et si je vous disais que vous n'avez pas besoin d'être un.e expert.e en intelligence artificielle ou en machine learning pour apporter certaines de ces fonctionnalités dans vos applications Android.
        Dans cette session, nous explorerons ce que ML Kit a à offrir pour ajouter assez facilement des fonctionnalités de machine learning optimisées pour le mobile. En se basant sur des examples de code, nous explorerons les principales API de Vision et Natural Language pour potentiellement débloquer de nouvelles idées dans vos applications."

